#!/usr/bin/env bash
# Write a Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line using while
i=1
while [ $i -le 10 ]
do
    if [ $i -ne 9 ]
    then
	echo "Best School"
    else
	echo -e "Best School\nHi"
    fi
    i=$((i + 1))
done
